namespace AJut.Text.AJson.SourceGenerators.Emit
{
    using System.Collections.Generic;
    using Microsoft.CodeAnalysis;

    /// <summary>
    /// Emits a single [ModuleInitializer] that registers each collected enum with the AJut
    /// <c>TypeIdRegistrar</c> under its runtime full name. This lets a boxed enum in a
    /// [JsonRuntimeTypeEval] object slot resolve via the registrar - a hard typeof reference, so trim
    /// / ReadyToRun safe - instead of an assembly-qualified name that Type.GetType cannot bind in a
    /// packaged app. The full name is taken from typeof(...).FullName at runtime so nested enums get
    /// their correct '+' separated name without the emitter having to reconstruct it.
    /// </summary>
    internal static class EnumRegistrationEmitter
    {
        public static string Emit (IEnumerable<INamedTypeSymbol> enums)
        {
            CodeBuilder cb = new CodeBuilder();

            cb.AppendLine("// <auto-generated/>");
            cb.AppendLine("// AJut.Core source-generated enum type-id registrations. Do not edit.");
            cb.AppendLine();
            cb.AppendLine("namespace AJut.Text.AJson.Generated");
            cb.OpenBrace();
            cb.AppendLine("using global::System.Runtime.CompilerServices;");
            cb.AppendLine();
            cb.AppendLine("internal static class _AJsonEnumTypeIdRegistrations");
            cb.OpenBrace();

            cb.AppendLine("[ModuleInitializer]");
            cb.AppendLine("internal static void Register()");
            cb.OpenBrace();
            foreach (INamedTypeSymbol enumType in enums)
            {
                string fqn = enumType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                cb.AppendLine($"global::AJut.TypeManagement.TypeIdRegistrar.RegisterTypeId(typeof({fqn}).FullName, typeof({fqn}));");
            }
            cb.CloseBrace();

            cb.CloseBrace();
            cb.CloseBrace();

            return cb.ToString();
        }
    }
}
