namespace AJut.Text.AJson.SourceGenerators.Emit
{
    using System.Collections.Generic;
    using System.Text;
    using AJut.Text.AJson.SourceGenerators.Model;

    /// <summary>
    /// Pure model-to-source step. Produces a single C# source string per SerializableTypeModel
    /// containing a static helper class with Write / Read methods plus a [ModuleInitializer]
    /// that registers them into the AJut.Core dispatch table.
    /// </summary>
    /// <remarks>
    /// The emitted code references AJut.Core's public surface only - JsonHelper, JsonBuilder,
    /// JsonValue, JsonInterpreterSettings, AJsonGenerationSupport, AJsonGeneratedDispatch.
    /// Nothing internal is touched, so the generated code lives happily in any consumer assembly.
    /// </remarks>
    internal static class SerializerEmitter
    {
        public static string Emit (SerializableTypeModel model)
        {
            CodeBuilder cb = new CodeBuilder();

            cb.AppendLine("// <auto-generated/>");
            cb.AppendLine("// AJut.Core source-generated AJson serializer. Do not edit.");
            cb.AppendLine("#nullable disable");
            cb.AppendLine("#pragma warning disable CS0162  // Unreachable code");
            cb.AppendLine("#pragma warning disable CS8019  // Unnecessary using");
            cb.AppendLine();
            cb.AppendLine("namespace AJut.Text.AJson.Generated");
            cb.OpenBrace();
            cb.AppendLine("using global::System;");
            cb.AppendLine("using global::System.Collections.Generic;");
            cb.AppendLine("using global::System.Runtime.CompilerServices;");
            cb.AppendLine("using global::AJut.Text.AJson;");
            cb.AppendLine();

            string helperClass = $"_AJsonSerializer_{model.MangledName}";
            cb.AppendLine($"internal static class {helperClass}");
            cb.OpenBrace();

            cb.AppendLine("[ModuleInitializer]");
            cb.AppendLine("internal static void Register()");
            cb.OpenBrace();
            cb.AppendLine($"global::AJut.Text.AJson.AJsonGeneratedDispatch.Register(typeof({model.FullyQualifiedTypeName}), Write, Read);");
            cb.CloseBrace();
            cb.AppendLine();

            EmitWriteMethod(cb, model);
            cb.AppendLine();
            EmitReadMethod(cb, model);

            cb.CloseBrace();
            cb.CloseBrace();
            cb.AppendLine();
            cb.AppendLine("#pragma warning restore CS8019");
            cb.AppendLine("#pragma warning restore CS0162");
            cb.AppendLine("#nullable restore");

            return cb.ToString();
        }

        // ===========================[ Write ]===========================
        private static void EmitWriteMethod (CodeBuilder cb, SerializableTypeModel model)
        {
            cb.AppendLine("public static void Write(global::System.Object instance, global::AJut.Text.AJson.JsonBuilder builder)");
            cb.OpenBrace();
            cb.AppendLine("if (instance == null) { return; }");
            cb.AppendLine($"{model.FullyQualifiedTypeName} obj = ({model.FullyQualifiedTypeName})instance;");

            // [JsonPropertyAsSelf] elevation - swap to the inner property's value and recurse via JsonHelper.
            if (!string.IsNullOrEmpty(model.PropertyAsSelfName))
            {
                cb.AppendLine($"global::System.Object elevated = obj.{model.PropertyAsSelfName};");
                cb.AppendLine("if (elevated == null) { return; }");
                cb.AppendLine("global::AJut.Text.AJson.JsonHelper.FillOutJsonBuilderForObject(elevated, builder);");
                cb.CloseBrace();
                return;
            }

            cb.AppendLine($"global::AJut.Text.AJson.JsonBuilder doc = global::AJut.Text.AJson.AJsonGenerationSupport.StartGeneratedDocument(builder, typeof({model.FullyQualifiedTypeName}));");

            foreach (PropertyModel prop in model.Properties)
            {
                if (!prop.HasGetter)
                {
                    continue;
                }
                EmitPropertyWrite(cb, prop);
            }

            cb.CloseBrace();
        }

        private static void EmitPropertyWrite (CodeBuilder cb, PropertyModel prop)
        {
            cb.AppendLine($"// {prop.Name} -> \"{prop.JsonKey}\"");
            string accessor = $"obj.{prop.Name}";
            bool needsNullCheck = !prop.IsValueType || prop.IsNullable;
            bool needsOmitGuard = prop.HasOmitIfDefault && (prop.HasExplicitOmitDefault || prop.IsValueType);

            cb.OpenBrace();

            if (needsNullCheck)
            {
                cb.AppendLine($"if ({accessor} != null)");
                cb.OpenBrace();
            }

            if (needsOmitGuard)
            {
                string valueExpr = prop.IsNullable ? $"{accessor}.Value" : accessor;
                string compareTo = prop.HasExplicitOmitDefault
                    ? prop.ExplicitOmitDefaultLiteral
                    : $"default({prop.UnderlyingTypeFullName})";
                cb.AppendLine($"if (!global::System.Collections.Generic.EqualityComparer<{prop.UnderlyingTypeFullName}>.Default.Equals({valueExpr}, {compareTo}))");
                cb.OpenBrace();
            }

            switch (prop.Kind)
            {
                case ePropertyKind.RuntimeTypeEval:
                    EmitWriteRuntimeTypeEval(cb, prop, accessor);
                    break;
                case ePropertyKind.SimpleValue:
                case ePropertyKind.Enum:
                case ePropertyKind.BuiltInCustom:
                    EmitWriteSimple(cb, prop, accessor);
                    break;
                case ePropertyKind.ComplexReference:
                case ePropertyKind.Collection:
                case ePropertyKind.Dictionary:
                    EmitWriteRecurse(cb, prop, accessor);
                    break;
                case ePropertyKind.Unsupported:
                    cb.AppendLine("// AJSON002: unsupported property type for source generation - skipped at emit time");
                    break;
            }

            if (needsOmitGuard)
            {
                cb.CloseBrace();
            }
            if (needsNullCheck)
            {
                cb.CloseBrace();
            }
            cb.CloseBrace();
        }

        private static void EmitWriteSimple (CodeBuilder cb, PropertyModel prop, string accessor)
        {
            string valueExpr = prop.IsNullable ? $"{accessor}.Value" : accessor;
            string isQuotedLiteral = prop.IsUsuallyQuoted ? "true" : "false";
            cb.AppendLine($"doc.AddProperty(\"{Escape(prop.JsonKey)}\", (global::System.Object){valueExpr}, isUsuallyQuoted: {isQuotedLiteral});");
        }

        private static void EmitWriteRecurse (CodeBuilder cb, PropertyModel prop, string accessor)
        {
            cb.AppendLine($"global::AJut.Text.AJson.JsonBuilder propBuilder = doc.StartProperty(\"{Escape(prop.JsonKey)}\");");
            cb.AppendLine($"global::AJut.Text.AJson.JsonHelper.FillOutJsonBuilderForObject({accessor}, propBuilder);");
        }

        private static void EmitWriteRuntimeTypeEval (CodeBuilder cb, PropertyModel prop, string accessor)
        {
            cb.AppendLine($"global::AJut.Text.AJson.JsonBuilder rteValueBuilder = global::AJut.Text.AJson.AJsonGenerationSupport.StartRuntimeTypeEvalProperty(doc, \"{Escape(prop.JsonKey)}\", {prop.RuntimeTypeEvalFlagLiteral}, {accessor}.GetType());");
            cb.AppendLine("if (rteValueBuilder != null)");
            cb.OpenBrace();
            cb.AppendLine($"global::AJut.Text.AJson.JsonHelper.FillOutJsonBuilderForObject({accessor}, rteValueBuilder);");
            cb.CloseBrace();
        }

        // ===========================[ Read ]===========================
        private static void EmitReadMethod (CodeBuilder cb, SerializableTypeModel model)
        {
            cb.AppendLine("public static global::System.Object Read(global::AJut.Text.AJson.JsonValue value, global::AJut.Text.AJson.JsonInterpreterSettings settings, global::AJut.Text.AJson.Json owner)");
            cb.OpenBrace();
            cb.AppendLine("if (value == null) { return null; }");
            cb.AppendLine("settings = settings ?? global::AJut.Text.AJson.JsonInterpreterSettings.Default;");

            // [JsonPropertyAsSelf] read-side: the json we have is the inner property's content; build instance + assign.
            if (!string.IsNullOrEmpty(model.PropertyAsSelfName))
            {
                PropertyModel asSelfProp = FindProperty(model, model.PropertyAsSelfName);
                if (asSelfProp != null && asSelfProp.HasSetter)
                {
                    cb.AppendLine($"{model.FullyQualifiedTypeName} elevatedHost = new {model.FullyQualifiedTypeName}();");
                    cb.AppendLine("global::AJut.Text.AJson.JsonValue elevatedSource = value;");
                    cb.AppendLine("if (value is global::AJut.Text.AJson.JsonDocument legacyDoc)");
                    cb.OpenBrace();
                    cb.AppendLine($"global::AJut.Text.AJson.JsonValue legacyMatch = legacyDoc.ValueFor(\"{Escape(model.PropertyAsSelfName)}\");");
                    cb.AppendLine("if (legacyMatch != null) { elevatedSource = legacyMatch; }");
                    cb.CloseBrace();
                    cb.AppendLine($"{asSelfProp.UnderlyingTypeFullName} elevatedInner = global::AJut.Text.AJson.JsonHelper.BuildObjectForJson<{asSelfProp.UnderlyingTypeFullName}>(elevatedSource, settings);");
                    cb.AppendLine($"elevatedHost.{model.PropertyAsSelfName} = elevatedInner;");
                    cb.AppendLine("return elevatedHost;");
                }
                else
                {
                    cb.AppendLine("return null;");
                }
                cb.CloseBrace();
                return;
            }

            cb.AppendLine("if (!(value is global::AJut.Text.AJson.JsonDocument doc))");
            cb.OpenBrace();
            cb.AppendLine("owner?.AddError(\"Generated reader expected a JsonDocument\");");
            cb.AppendLine("return null;");
            cb.CloseBrace();

            // Construct instance.
            if (model.HasParameterlessConstructor || model.IsValueType)
            {
                cb.AppendLine($"{model.FullyQualifiedTypeName} result = new {model.FullyQualifiedTypeName}();");
            }
            else
            {
                // Fall back to ConstructInstanceFor (the custom-constructor path) - the AJSON001
                // diagnostic should have fired at compile time already, but keep the runtime path
                // sound so the generated code at least compiles.
                cb.AppendLine($"{model.FullyQualifiedTypeName} result = ({model.FullyQualifiedTypeName})settings.ConstructInstanceFor(typeof({model.FullyQualifiedTypeName}), value, owner);");
                cb.AppendLine("if (result == null) { return null; }");
            }

            // Property-by-property switch on the json key.
            cb.AppendLine("foreach (global::System.Collections.Generic.KeyValuePair<global::System.String, global::AJut.Text.AJson.JsonValue> kvp in doc)");
            cb.OpenBrace();
            cb.AppendLine("switch (kvp.Key)");
            cb.OpenBrace();

            HashSet<string> emittedKeys = new HashSet<string>();
            foreach (PropertyModel prop in model.Properties)
            {
                if (!prop.HasSetter)
                {
                    continue;
                }
                if (!emittedKeys.Add(prop.JsonKey))
                {
                    continue;
                }
                cb.AppendLine($"case \"{Escape(prop.JsonKey)}\":");
                cb.IndentBlock(() =>
                {
                    EmitPropertyRead(cb, prop);
                    cb.AppendLine("break;");
                });
            }
            cb.CloseBrace();   // closes switch
            cb.CloseBrace();   // closes foreach

            cb.AppendLine("return result;");
            cb.CloseBrace();
        }

        private static PropertyModel FindProperty (SerializableTypeModel model, string name)
        {
            foreach (PropertyModel p in model.Properties)
            {
                if (p.Name == name)
                {
                    return p;
                }
            }
            return null;
        }

        private static void EmitPropertyRead (CodeBuilder cb, PropertyModel prop)
        {
            switch (prop.Kind)
            {
                case ePropertyKind.RuntimeTypeEval:
                    cb.AppendLine($"global::System.Object rteRead = global::AJut.Text.AJson.AJsonGenerationSupport.ReadRuntimeTypeEvalProperty(kvp.Value, settings, owner);");
                    cb.AppendLine($"if (rteRead != null) {{ result.{prop.Name} = ({prop.TypeFullName})rteRead; }}");
                    break;
                default:
                    if (prop.IsNullable)
                    {
                        cb.AppendLine($"result.{prop.Name} = global::AJut.Text.AJson.JsonHelper.BuildObjectForJson<{prop.TypeFullName}>(kvp.Value, settings);");
                    }
                    else
                    {
                        cb.AppendLine($"result.{prop.Name} = global::AJut.Text.AJson.JsonHelper.BuildObjectForJson<{prop.TypeFullName}>(kvp.Value, settings);");
                    }
                    break;
            }
        }

        // ===========================[ Helpers ]===========================
        private static string Escape (string s)
        {
            if (string.IsNullOrEmpty(s))
            {
                return string.Empty;
            }
            StringBuilder sb = new StringBuilder(s.Length);
            foreach (char c in s)
            {
                switch (c)
                {
                    case '\\': sb.Append("\\\\"); break;
                    case '"': sb.Append("\\\""); break;
                    case '\n': sb.Append("\\n"); break;
                    case '\r': sb.Append("\\r"); break;
                    case '\t': sb.Append("\\t"); break;
                    default: sb.Append(c); break;
                }
            }
            return sb.ToString();
        }
    }
}
