name: Publish all AJut packages -> Nuget (Automatic)

on:
  pull_request:
    branches:
      - main
    types:
      - closed

# This job will only run if the pull request was merged AND the 'publish-nuget' label was added.
jobs:
  build:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'publish-nuget')
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get PR Number
      id: get_pr_number
      run: |
        $prNumber = ${{ github.event.pull_request.number }}
        echo "PR_NUMBER=$prNumber" >> $env:GITHUB_ENV
      shell: pwsh
      
    - name: Build Projects
      run: ./.github/scripts/build-targets.ps1 -prNumber ${{ env.PR_NUMBER }}
      shell: pwsh

  test:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Test Projects
      run: ./.github/scripts/test-targets.ps1
      shell: pwsh
      
  publish:
    needs: [build, test]
    runs-on: windows-latest
    env:
      NUGET_API_KEY: ${{ secrets.NUGETPUBLISHKEY }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get PR Number
      id: get_pr_number
      run: |
        $prNumber = ${{ github.event.pull_request.number }}
        echo "PR_NUMBER=$prNumber" >> $env:GITHUB_ENV
      shell: pwsh
      
    - name: Publish Projects
      run: ./.github/scripts/publish-targets.ps1 -prNumber ${{ env.PR_NUMBER }} -apiKey $env:NUGET_API_KEY
      shell: pwsh
