name: Publish all AJut packages -> Nuget (Automatic)

on:
  pull_request:
    branches:
      - main
    types:
      - closed

# This job will only run if the pull request was merged AND the 'publish-nuget' label was added.
jobs:
  build_test_publish:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'publish-nuget')
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}
      NUGETPUBLISHKEY: ${{ secrets.NUGETPUBLISHKEY }}
    steps:
    - name: Get PR Number
      id: get_pr_number
      run: |
        $prNumber = ${{ github.event.pull_request.number }}
        echo "PR_NUMBER=$prNumber" >> $env:GITHUB_ENV
      shell: pwsh
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build AJut Libraries
      run: ./.github/scripts/build-targets.ps1 -prNumber ${{ env.PR_NUMBER }}
    
    - name: Test AJut Libraries
      run: ./.github/scripts/test-targets.ps1

    - name: Publish AJut Libraries
      run: ./.github/scripts/publish-targets.ps1 -prNumber ${{ env.PR_NUMBER }} -apiKey $env:NUGET_API_KEY