name: Publish To Nuget (Manual, Combined)

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: 'Pull Request Number'
        required: true
        type: number
      
      # The following inputs are should match from ProjectOrder.json
      # For now, I don't know how to pull this in dynamically, so we'll keep it hard coded.
      buildAJutCore:
        description: 'Build AJut.Core'
        required: false
        type: boolean
        default: true
      buildAJutUX:
        description: 'Build AJut.UX'
        required: false
        type: boolean
        default: false
      buildAJutUXWpf:
        description: 'Build AJut.UX.Wpf'
        required: false
        type: boolean
        default: false
      buildAJutUXWinUI3:
        description: 'Build AJut.UX.WinUI3'
        required: false
        type: boolean
        default: false

jobs:
  build_test_publish:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}
      NUGETPUBLISHKEY: ${{ secrets.NUGETPUBLISHKEY }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build AJut Libraries
      run: |
        $projectsToBuildJson = '${{ toJSON(github.event.inputs) }}'
        ./.github/scripts/build-targets.ps1 -prNumber ${{ github.event.inputs.prNumber }} -projectsToBuild $projectsToBuildJson
    
    - name: Test AJut Libraries
      run: |
        ./.github/scripts/test-targets.ps1

    - name: Publish AJut Libraries
      run: |
        ./.github/scripts/publish-targets.ps1 -prNumber ${{ github.event.inputs.prNumber }} -apiKey "$env:NUGETPUBLISHKEY"