name: PR Merged, Update Next Publish Version Numbers

on:
  pull_request:
    branches: [ main ]
    types: [closed]

jobs:
  update-variable:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest

    steps:
    - name: Initial decleration
      run: echo "Last PR Saver (Version 2)"

    - name: Set new value for variable
      run: |
         $headers = @{
            Authorization = "Bearer ${{ secrets.GH_TOKEN }}"
            Accept = "application/vnd.github+json"
         }
         $url = "https://api.github.com/repos/ajbadaj/ajut/actions/variables/LAST_MERGED_PR"
         $body = @{
           name = "last_merged_PR"
           value = "${{ github.event.pull_request.number }}"
         } | ConvertTo-Json
         echo $body
         Invoke-RestMethod -Uri $url -Method PATCH -Headers $headers -Body $body
      shell: pwsh