name: PR Merged, Update Next Publish Version Numbers

on:
  pull_request:
    branches: [ main ]
    types: [closed]

jobs:
  update-version:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update AJut.Core version number for next run
      run: |
        $csprojPath = "libs/AJut.Core/AJut.Core.csproj"
        [xml]$csproj = Get-Content $csprojPath
        $csproj.Project.PropertyGroup.Version = "${{ vars.AJUT_CORE_BASELINE_VERSION }}.${{ github.event.pull_request.number }}"
        $csproj.Save($csprojPath)
      shell: pwsh

    - name: Update AJut.UX.Wpf version number for next run
      run: |
        $csprojPath = "libs/AJut.UX.Wpf/AJut.UX.Wpf.csproj"
        [xml]$csproj = Get-Content $csprojPath
        $csproj.Project.PropertyGroup.Version = "${{ vars.AJUT_UX_WPF_BASELINE_VERSION }}.${{ github.event.pull_request.number }}"
        $csproj.Save($csprojPath)
      shell: pwsh

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add libs/AJut.Core/AJut.Core.csproj
        git add libs/AJut.UX.Wpf/AJut.UX.Wpf.csproj
        git commit -m "Update version to use last submitted pr ${{ github.event.pull_request.number }}"
        git push
      shell: pwsh