name: Publish [AJut.UX.Wpf] -> Nuget

on:
  workflow_dispatch:

jobs:
  build_ajut_release_publish_and_test:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
    - name: Initial decleration
      run: echo "Publish UX (WPF) To Nuget (Version 1)"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build AJut.UX.Wpf
      run: dotnet build libs/AJut.UX.Wpf/AJut.UX.Wpf.csproj --no-restore --configuration Release

    - name: Publish AJut Libraries to NuGet
      run: |
          $uxWpfNugetFile = Get-ChildItem -Path "./" -Recurse -Filter "AJut.UX.Wpf.*.nupkg" | Where-Object { $_.FullName -match "Release" } | Select-Object -First 1

          echo "UX.Wpf found as $uxWpfNugetFile"
          
          echo "Publishing..."
          dotnet nuget push "$($uxWpfNugetFile.FullName)" --api-key ${{ secrets.NUGETPUBLISHKEY }} --source https://api.nuget.org/v3/index.json

      shell: pwsh
