name: Publish to Nuget

on:
  workflow_dispatch:

jobs:
  build_ajut_core_versioned_release_publish_and_test:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
    - name: Initial decleration
      run: echo "Publish To Nuget (Version 1)"

    - name: Testing Env Values
      run: echo "AJut.Core Version Number saved as ${{ vars.AJUT_CORE_BASELINE_VERSION }}.${{ vars.last_merged_PR }}"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Core
      run: dotnet build libs/AJut.Core/AJut.Core.csproj --no-restore --configuration Release /p:Version=${{ vars.AJUT_CORE_BASELINE_VERSION }}.${{ vars.last_merged_PR }}

    - name: Run unit tests
      run: dotnet test --configuration Release

    - name: Publish AJut.Core to NuGet
      run: |
          $file = Get-ChildItem -Path "./" -Recurse -Filter "AJut.Core.${{ vars.AJUT_CORE_BASELINE_VERSION }}.${{ vars.last_merged_PR }}.nupkg" | Where-Object { $_.FullName -match "Release" } | Select-Object -First 1
          if ($file) {
            dotnet nuget push "$($file.FullName)" --api-key ${{ secrets.NUGETPUBLISHKEY }} --source https://api.nuget.org/v3/index.json
          } else {
            throw "File not found"
          }
      shell: pwsh
