name: Publish AJut to Nuget

on:
  workflow_dispatch:

jobs:
  build_ajut_release_publish_and_test:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
    - name: Initial decleration
      run: echo "Publish To Nuget (Version 1)"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build AJut.Core
      run: dotnet build libs/AJut.Core/AJut.Core.csproj --no-restore --configuration Release

    - name: Build AJut.UX.Wpf
      run: dotnet build libs/AJut.UX.Wpf/AJut.UX.Wpf.csproj --no-restore --configuration Release

    - name: Run unit tests
      run: dotnet test --configuration Release

    - name: Publish AJut Libraries to NuGet
      run: |
          $coreNugetFile = Get-ChildItem -Path "./" -Recurse -Filter "AJut.Core.${{ vars.AJUT_CORE_BASELINE_VERSION }}.${{ vars.last_merged_PR }}.nupkg" | Where-Object { $_.FullName -match "Release" } | Select-Object -First 1
          $uxWpfNugetFile = Get-ChildItem -Path "./" -Recurse -Filter "AJut.UX.Wpf.${{ vars.AJUT_UX_WPF_BASELINE_VERSION }}.${{ vars.last_merged_PR }}.nupkg" | Where-Object { $_.FullName -match "Release" } | Select-Object -First 1
          if ($coreNugetFile && $uxWpfNugetFile) {
            dotnet nuget push "$($coreNugetFile.FullName)" --api-key ${{ secrets.NUGETPUBLISHKEY }} --source https://api.nuget.org/v3/index.json
            dotnet nuget push "$($uxWpfNugetFile.FullName)" --api-key ${{ secrets.NUGETPUBLISHKEY }} --source https://api.nuget.org/v3/index.json
          } else if (!$coreNugetFile) {
            throw "Core file not found"
          } else
            throw "UX.Wpf file not found"
          }
      shell: pwsh
