name: Publish AJut -> Nuget

# ============================================================================================================
# This is manual only for now. I'd like to do it automatically, but after messing up the build for over a day
#   it's not worth it right now IMO :)
# ============================================================================================================

on:
  workflow_dispatch:
    inputs:
      # The following inputs are should match from ProjectOrder.json
      # For now, I don't know how to pull this in dynamically, so we'll keep it hard coded.
      buildAJutCore:
        description: 'Build & Publish AJut.Core'
        required: false
        type: boolean
        default: true
      buildAJutUX:
        description: 'Build & Publish  AJut.UX'
        required: false
        type: boolean
        default: true
      buildAJutUXWpf:
        description: 'Build & Publish  AJut.UX.Wpf'
        required: false
        type: boolean
        default: true
      buildAJutUXWinUI3:
        description: 'Build & Publish  AJut.UX.WinUI3'
        required: false
        type: boolean
        default: true
      dryRunPublish:
        description: 'Is this a dry run? (nothing will be published if true)'
        type: boolean
        default: false

# This job will now run when a .csproj file is pushed to main or is manually dispatched
jobs:
  build_test_publish:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}
      NUGETPUBLISHKEY: ${{ secrets.NUGETPUBLISHKEY }}
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build AJut Libraries
      env:
        PROJECTS_TO_BUILD: ${{ toJSON(github.event.inputs) }}
      run: |
        ./.github/scripts/build-targets.ps1 -projectsToBuild $env:PROJECTS_TO_BUILD
        # # On push, we diff to find target projects
        # if ("${{ github.event_name }}" -eq "push") {
        #   ./.github/scripts/build-targets.ps1 -prHeadSHA ${{ github.event.after }} -prBaseSHA ${{ github.event.before }}
        # } else {
        #   # On manual dispatch, we have the targets built in
        #   ./.github/scripts/build-targets.ps1 -projectsToBuild $env:PROJECTS_TO_BUILD
        # }

    - name: Test AJut Libraries
      run: ./.github/scripts/test-targets.ps1

    - name: Publish AJut Libraries
      run: |
        if (${{ github.event.inputs.dryRunPublish }}) {
            ./.github/scripts/publish-targets.ps1 -apiKey "$env:NUGETPUBLISHKEY" -dryRun
        } else{
            ./.github/scripts/publish-targets.ps1 -apiKey "$env:NUGETPUBLISHKEY"
        }
        