name: Publish to Nuget

on:
  workflow_dispatch:

jobs:
  build_and_test_all:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
    - name: Initial decleration
      run: echo "Publish To Nuget (Version 17)"

    - name: Stocking Environment with Version Numbers
      run: |
        echo "AJUT_CORE_VERSION=${{ vars.AJUT_CORE_BASELINE_VERSION }}.${{ vars.last_merged_PR }}" >> $GITHUB_ENV
        echo "AJUT_UX_WPF_VERSION=${{ vars.AJUT_UX_WPF_BASELINE_VERSION }}.${{ vars.last_merged_PR }}" >> $GITHUB_ENV
        echo "VersionNumber=1.2" >> $GITHUB_ENV

    - name: Testing Env Values
      run: |
        echo "The value of VersionNumber is ${{ env.VersionNumber }}"
        echo "AJut.Core Version Number saved as ${{ env.AJUT_CORE_VERSION }}"
        echo "AJut.UX.Wpf Version Number saved as ${{ env.AJUT_UX_WPF_VERSION }}"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Core
      run: dotnet build libs/AJut.Core/AJut.Core.csproj --no-restore --configuration Release /p:Version=${{ env.AJUT_CORE_VERSION }}

    - name: Build WPF
      run: dotnet build libs/AJut.UX.Wpf/AJut.UX.Wpf.csproj --no-restore --configuration Release  /p:Version=${{ env.AJUT_UX_WPF_VERSION }}

    - name: Run unit tests
      run: dotnet test --configuration Release

  publish_ajut_core:
    runs-on: windows-latest
    needs: build_and_test_all

    steps:
    - name: Publish AJut.Core to NuGet
      run: |
          $filePath = "libs/AJut.Core/bin/Release/ajut.core.${{ env.AJUT_CORE_VERSION }}.nupkg"
          if (Test-Path $filePath) {
              echo "Publishing would look like this: dotnet nuget push $filePath --api-key ${{ secrets.NUGETPUBLISHKEY }} --source https://api.nuget.org/v3/index.json"
          } else {
              throw "File not found: $filePath"
          }
      shell: pwsh

  publish_ajut_ux_wpf:
    runs-on: windows-latest
    needs: build_and_test_all

    steps:
    - name: Publish AJut.UX.Wpf to NuGet
      run: |
          echo "Using Concatenated for core ${{ env.AJUT_CORE_VERSION }}"
          for file in libs/AJut.Core/bin/Release/*.nupkg; do
            echo "$file"
          done
      #run: dotnet nuget push libs/AJut.UX.Wpf/bin/Release/*.nupkg --api-key ${{ secrets.NUGETPUBLISHKEY }} --source https://api.nuget.org/v3/index.json