name: Publish to Nuget

on:
  workflow_dispatch:

jobs:
  build_and_test_all:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
    - name: Initial decleration
      run: echo "Publish To Nuget (Version 18)"

    - name: Testing Env Values
      run: |
        echo "AJut.Core Version Number saved as ${{ vars.AJUT_CORE_BASELINE_VERSION }}.${{ vars.last_merged_PR }}"
        echo "AJut.UX.Wpf Version Number saved as ${{ vars.AJUT_UX_WPF_BASELINE_VERSION }}.${{ vars.last_merged_PR }}"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Core
      run: dotnet build libs/AJut.Core/AJut.Core.csproj --no-restore --configuration Release /p:Version=${{ vars.AJUT_CORE_BASELINE_VERSION }}.${{ vars.last_merged_PR }}

    - name: Build WPF
      run: dotnet build libs/AJut.UX.Wpf/AJut.UX.Wpf.csproj --no-restore --configuration Release  /p:Version=${{ vars.AJUT_UX_WPF_BASELINE_VERSION }}.${{ vars.last_merged_PR }}

    - name: Run unit tests
      run: dotnet test --configuration Release

  publish_ajut_core:
    runs-on: windows-latest
    needs: build_and_test_all

    steps:
    - name: Publish AJut.Core to NuGet
      run: |
          $filePath = "libs/AJut.Core/bin/Release/ajut.core.${{ vars.AJUT_CORE_BASELINE_VERSION }}.${{ vars.last_merged_PR }}.nupkg"
          if (Test-Path $filePath) {
              echo "Publishing would look like this: dotnet nuget push $filePath --api-key ${{ secrets.NUGETPUBLISHKEY }} --source https://api.nuget.org/v3/index.json"
          } else {
              throw "File not found: $filePath"
          }
      shell: pwsh

  publish_ajut_ux_wpf:
    runs-on: windows-latest
    needs: build_and_test_all

    steps:
    - name: Publish AJut.Core to NuGet
      run: |
          $filePath = "libs/AJut.UX.Wpf/bin/Release/ajut.ux.wpf.${{ vars.AJUT_UX_WPF_BASELINE_VERSION }}.${{ vars.last_merged_PR }}.nupkg"
          if (Test-Path $filePath) {
              echo "Publishing would look like this: dotnet nuget push $filePath --api-key ${{ secrets.NUGETPUBLISHKEY }} --source https://api.nuget.org/v3/index.json"
          } else {
              throw "File not found: $filePath"
          }
      shell: pwsh