name: Set & Push Version

# NOTE: This is not going to work until I figure out how to exclude the bot from
# restrictions on pushing

on:
  # If run manually
  workflow_dispatch:
    inputs:
      prNumber:
        description: 'Pull Request Number (the final int in version number). NOTE: will set all projects when run manually.'
        required: true
        type: number
  # If run automatically
  pull_request:
   types:
     - closed
   branches:
     - main

jobs:
  update_version:
    #if: github.event.pull_request.merged == true
    runs-on: windows-latest
    steps:
    
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.CICDAUTOMATION_DEPLOYMENT_KEY }}
        fetch-depth: 0 # Get all history to correctly determine changed files

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Set PR Number
      run: |
        if ("${{ github.event.inputs.prNumber }}" -ne "") {
          $prNumber = ${{ github.event.inputs.prNumber }}
          echo "PR_NUMBER=$prNumber" >> $env:GITHUB_ENV
        } else {
          $prNumber = ${{ github.event.pull_request.number }}
          echo "PR_NUMBER=$prNumber" >> $env:GITHUB_ENV
        }
      shell: pwsh
          

    - name: Set new version numbers
      run: |
          if ("${{ github.event.inputs.prNumber }}" -ne "") {
            Write-Host "This is a manual run."
            $changes = ./.github/scripts/set-version-numbers.ps1 -prNumber ${{ env.PR_NUMBER }}
          } else {
            Write-Host "This is an automatic run."
            $changes = ./.github/scripts/set-version-numbers.ps1 -prNumber ${{ env.PR_NUMBER }}  -prHeadSHA ${{ github.event.pull_request.head.sha }} -prBaseSHA ${{ github.event.pull_request.base.sha }}
          }

          if ($changes.Count -gt 0) {
            echo "SHOULD_RUN=true" >> $env:GITHUB_ENV
            $preview = $changes.Count
            Write-Host "$preview projects updated, continuing."
          } else {
            echo "SHOULD_RUN=false" >> $env:GITHUB_ENV
            Write-Host "No projects changed, skipping version update."
          }
      shell: pwsh

    - name: Commit and push changes
      if: env.SHOULD_RUN == 'true'
      env:
        GH_ADMIN_ACCESS_TOKEN: ${{ secrets.CICDAUTOMATION_ACCESS_TOKEN }}
        GH_TOKEN: ${{ github.token }}
      run: |
        git remote set-url origin git@github.com:${{ github.repository }}.git
        git add .
        git commit -m "Automated commit from workflow"
        git push origin HEAD
        